[2022-02-07 12:12:23,501] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2021-12-01T23:00:00+00:00 [queued]>
[2022-02-07 12:12:23,514] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2021-12-01T23:00:00+00:00 [queued]>
[2022-02-07 12:12:23,514] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 12:12:23,514] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-07 12:12:23,514] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 12:12:23,633] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-12-01 23:00:00+00:00
[2022-02-07 12:12:23,642] {standard_task_runner.py:52} INFO - Started process 2426 to run task
[2022-02-07 12:12:23,649] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellowTX_HW_data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2021-12-01T23:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/yellowTX_data_ingest_gcs_dag.py', '--cfg-path', '/tmp/tmpc6k0fc6x', '--error-file', '/tmp/tmp8zl7rhff']
[2022-02-07 12:12:23,650] {standard_task_runner.py:77} INFO - Job 68: Subtask download_dataset_task
[2022-02-07 12:12:23,860] {logging_mixin.py:109} INFO - Running <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2021-12-01T23:00:00+00:00 [running]> on host 52b8b55537b2
[2022-02-07 12:12:23,977] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-07 12:12:24,289] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellowTX_HW_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-12-01T23:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-01T23:00:00+00:00
[2022-02-07 12:12:24,299] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-07 12:12:24,300] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-12.csv > /opt/***/yellow_tripdata_2021-12.csv']
[2022-02-07 12:12:24,336] {subprocess.py:85} INFO - Output:
[2022-02-07 12:12:24,527] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-07 12:12:26,231] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellowTX_HW_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20211201T230000, start_date=20220207T121223, end_date=20220207T121226
[2022-02-07 12:12:30,355] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-07 12:12:34,662] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-07 13:15:51,704] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2021-12-01T23:00:00+00:00 [queued]>
[2022-02-07 13:15:51,720] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2021-12-01T23:00:00+00:00 [queued]>
[2022-02-07 13:15:51,720] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 13:15:51,720] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-07 13:15:51,720] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 13:15:51,736] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-12-01 23:00:00+00:00
[2022-02-07 13:15:51,742] {standard_task_runner.py:52} INFO - Started process 901 to run task
[2022-02-07 13:15:51,750] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellowTX_HW_data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2021-12-01T23:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/yellowTX_data_ingest_gcs_dag.py', '--cfg-path', '/tmp/tmp4d7311y3', '--error-file', '/tmp/tmph9yhw8j2']
[2022-02-07 13:15:51,751] {standard_task_runner.py:77} INFO - Job 146: Subtask download_dataset_task
[2022-02-07 13:15:51,846] {logging_mixin.py:109} INFO - Running <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2021-12-01T23:00:00+00:00 [running]> on host 4f748fac91e5
[2022-02-07 13:15:51,929] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-07 13:15:51,961] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellowTX_HW_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-12-01T23:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-01T23:00:00+00:00
[2022-02-07 13:15:51,962] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-07 13:15:51,963] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-12.csv > /opt/***/yellow_tripdata_2021-12.csv']
[2022-02-07 13:15:51,978] {subprocess.py:85} INFO - Output:
[2022-02-07 13:15:51,997] {subprocess.py:89} INFO - curl: (6) Could not resolve host: s3.amazonaws.com
[2022-02-07 13:15:51,998] {subprocess.py:93} INFO - Command exited with return code 6
[2022-02-07 13:15:52,016] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-02-07 13:15:52,024] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=yellowTX_HW_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20211201T230000, start_date=20220207T131551, end_date=20220207T131552
[2022-02-07 13:15:52,044] {standard_task_runner.py:92} ERROR - Failed to execute job 146 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-02-07 13:15:52,085] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-07 13:15:52,133] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
