[2022-02-07 12:11:11,603] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2020-11-01T23:00:00+00:00 [queued]>
[2022-02-07 12:11:11,726] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2020-11-01T23:00:00+00:00 [queued]>
[2022-02-07 12:11:11,726] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 12:11:11,727] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-07 12:11:11,727] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 12:11:11,830] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-11-01 23:00:00+00:00
[2022-02-07 12:11:11,924] {standard_task_runner.py:52} INFO - Started process 2217 to run task
[2022-02-07 12:11:11,979] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellowTX_HW_data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2020-11-01T23:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/yellowTX_data_ingest_gcs_dag.py', '--cfg-path', '/tmp/tmpn5j4e05f', '--error-file', '/tmp/tmp_672os1b']
[2022-02-07 12:11:11,984] {standard_task_runner.py:77} INFO - Job 38: Subtask download_dataset_task
[2022-02-07 12:11:12,344] {logging_mixin.py:109} INFO - Running <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2020-11-01T23:00:00+00:00 [running]> on host 52b8b55537b2
[2022-02-07 12:11:12,624] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-07 12:11:12,800] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellowTX_HW_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-11-01T23:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-11-01T23:00:00+00:00
[2022-02-07 12:11:12,801] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-07 12:11:12,802] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-11.csv > /opt/***/yellow_tripdata_2020-11.csv']
[2022-02-07 12:11:12,872] {subprocess.py:85} INFO - Output:
[2022-02-07 12:11:17,245] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-07 12:11:17,536] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellowTX_HW_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20201101T230000, start_date=20220207T121111, end_date=20220207T121117
[2022-02-07 12:11:17,865] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-07 12:11:18,095] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-07 13:15:35,363] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2020-11-01T23:00:00+00:00 [queued]>
[2022-02-07 13:15:35,419] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2020-11-01T23:00:00+00:00 [queued]>
[2022-02-07 13:15:35,420] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 13:15:35,420] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-07 13:15:35,420] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 13:15:35,470] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-11-01 23:00:00+00:00
[2022-02-07 13:15:35,479] {standard_task_runner.py:52} INFO - Started process 805 to run task
[2022-02-07 13:15:35,495] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellowTX_HW_data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2020-11-01T23:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/yellowTX_data_ingest_gcs_dag.py', '--cfg-path', '/tmp/tmp81pqw310', '--error-file', '/tmp/tmpa8bq3haq']
[2022-02-07 13:15:35,521] {standard_task_runner.py:77} INFO - Job 131: Subtask download_dataset_task
[2022-02-07 13:15:35,739] {logging_mixin.py:109} INFO - Running <TaskInstance: yellowTX_HW_data_ingestion_gcs_dag.download_dataset_task scheduled__2020-11-01T23:00:00+00:00 [running]> on host 4f748fac91e5
[2022-02-07 13:15:35,898] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-07 13:15:35,971] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellowTX_HW_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-11-01T23:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-11-01T23:00:00+00:00
[2022-02-07 13:15:35,972] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-07 13:15:35,973] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-11.csv > /opt/***/yellow_tripdata_2020-11.csv']
[2022-02-07 13:15:36,037] {subprocess.py:85} INFO - Output:
[2022-02-07 13:15:36,080] {subprocess.py:89} INFO - curl: (6) Could not resolve host: s3.amazonaws.com
[2022-02-07 13:15:36,080] {subprocess.py:93} INFO - Command exited with return code 6
[2022-02-07 13:15:36,266] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-02-07 13:15:36,290] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=yellowTX_HW_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20201101T230000, start_date=20220207T131535, end_date=20220207T131536
[2022-02-07 13:15:36,402] {standard_task_runner.py:92} ERROR - Failed to execute job 131 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-02-07 13:15:36,506] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-07 13:15:36,972] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
